"""rename department

Revision ID: 8552688ba0c8
Revises: 4c7c32bdb5bc
Create Date: 2024-01-27 21:54:29.902695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8552688ba0c8'
down_revision = '4c7c32bdb5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
